### ISSUE TITLE
Failed Identification of Local mis-assemblies/false chimeras

### ISSUE THREAD

**Issue by jy-ai** [azizmithani/roast#2] opened 2024-10-25 01:50 UTC
Hi,
I keep getting this error running roast: 
Identification of Local mis-assemblies/false chimeras: Process started
[1]    1028087 segmentation fault (core dumped) 

Do you know how to resolve this issue?

Following is my code：
 ../roast --supertranscript_assembly AT_test_ST.fasta --fastq_1 AT_test_1.fastq.gz AT_test_1.fastq.gz --fastq_2 AT_test_2.fastq.gz AT_test_2.fastq.gz --threads 10 --threadsForSamSort 2 --output_dir . --inner_itr 3 --outer_itr 3 --max_memory_TRINITY 30 --memForSamSort 5000

No. of contigs in initial assembly: 
8329
Outer iteration:1 started.
Inner iteration:1 started.
1-1: Alignment started for fragmented and partial contigs process using soft-clipping

Alignment ended

read length of this data is: 101
1-1: Assembly extension using soft clipped reads started
Extended incomplete contigs using soft-clipping at iteration 1-1: 2631
Assembly extension using soft clipped reads ended

1-1: Fastq files filtering process started.
Fastq file filtering step ended

Inner iteration:2 started.
1-2: Alignment started for fragmented and partial contigs process using soft-clipping

Alignment ended

1-2: Assembly extension using soft clipped reads started
Extended incomplete contigs using soft-clipping at iteration 1-2: 26
Assembly extension using soft clipped reads ended

1-2: Fastq files filtering process started.
Fastq file filtering step ended

Inner iteration:3 started.
1-3: Alignment started for fragmented and partial contigs process using soft-clipping

Alignment ended

1-3: Assembly extension using soft clipped reads started
Extended incomplete contigs using soft-clipping at iteration 1-3: 0
Assembly extension using soft clipped reads ended

1-3: Fastq files filtering process started.
Fastq file filtering step ended

***** Assembly merging using soft-clipped-extended ends: Process started *****

Merged incomplete contigs using Soft-clipping at iteration 1-4: 105
***** Assembly extension and merging using soft clipped reads: Process completed *****

1: Re-alignment on updated assembly for fragmented and partial contigs process using Unmapped and discordantly mapped reads

1: Assembly extension and merging using Unmapped and discordantly mapped reads: process started
No. of extended contigs by Cap3 at iteration : 85
Merged fragmented contigs using Reads Islands at iteration 1: 71

*****  Assembly extension and merging using Unmapped and discordantly mapped reads: process completed  *****

1: Re-alignment on updated assembly for Local mis-assemblies/false chimeras identification process

1: Identification of Local mis-assemblies/false chimeras: Process started
[1]    1028087 segmentation fault (core dumped)  ../roast --supertranscript_assembly AT_test_ST.fasta --fastq_1   --fastq_2  

Thanks!

**Comment by Shabbirm21** [comment] 2024-10-27 13:22
Hi Jy,

This is not a coding error, its usully occur when code is trying to get some data and give it some memory but data is not there or not compatible. Can you please confirm if you have enough space on your drive where new files are generated? Also can you paste content of last generated file at this step "Assembly extension and merging using Unmapped and discordantly mapped reads: process completed" and check if this driectory has generated sam/bam files after this step "1: Re-alignment on updated assembly for Local mis-assemblies/false chimeras identification process"? 

also if possible please paste output of this command "ls -lh -t" from the drive where all outputs are.

 Thanks,
 Madiha

**Comment by jy-ai** [comment] 2024-10-28 08:07
Hi Madiha,  
Thank you for your response.  

I confirm I have enough space on my drive (~4.3T).  
This is all files generated in Intermediate_improved_assemblies folder:
![EAD37C564BCE5CA18450E2E0FC6E8017](https://github.com/user-attachments/assets/7faf9f0c-d262-45f4-908b-ebc38069c84e)
But I still get this error:
1: Identification of Local mis-assemblies/false chimeras: Process started
[1]    3813807 segmentation fault (core dumped) 

Thanks,
Jy

**Comment by Shabbirm21** [comment] 2024-11-03 13:01
Hi Jy,

Thanks for sharing screen shot and apologies for late response. 

I couldn't reproduce this error , Is it possible to run 'ls -lh -t' and share screen? I am interested in seeing the size of generated files specifically size of latest generated fatsa file (Improved_assembly_RI_1.fasta) and alignment files for this step. Also, it would be help ful if you could screenshot initial few lines of "Improved_assembly_RI_1.fasta" file.

You are getting error at the very first step of Identification of Local mis-assemblies/false chimeras which seems like happening due to inappropriate fasta or alignment files. 

Thanks,
Madiha

**Comment by jy-ai** [comment] 2024-11-04 09:21
Hi Madiha,
Thank you for your response and my apologies for the wrong screen.

I re-ran the code and still got the same error.

1: Identification of Local mis-assemblies/false chimeras: Process started
[1]    3532710 segmentation fault (core dumped) 

This is all files generated in the Intermediate_improved_assemblies folder:
![5C6C2DF987C6DC051C0807A17150233F](https://github.com/user-attachments/assets/39459100-f6ad-4d0a-9703-58b42ec8b68f)

This is the initial few lines of the "Improved_assembly_RI_1.fasta" file:
![D52C1A3365AF1E3C714D9F13CBDC9F00](https://github.com/user-attachments/assets/9a05856c-e548-45a5-a3c5-5f7a7e3dc312)

Thanks,
Jy

**Comment by Songmg-Nwafu** [comment] 2024-11-04 14:07
Hi, Madiha.
I also got the same error. Segmentation fault (core dumped).
I created the environment in docker container.

**Comment by Shabbirm21** [comment] 2024-11-05 16:00
Hi @Songmg-Nwafu are you also getting error at the same step " Identification of Local mis-assemblies/false chimeras"?

@jy-ai did you manage to install CUFFLINKS properly? Because I can't see cufflinks output file(transcripts.gtf) in your output folder. CUFFLINKS comes seperately in external tool folder and need to run this "unzip external_tools/cufflinks.zip" because of size issue it is in compressed form. Other option is get fresh  cufflink binary file, make it executable and put in external tools folder. 

Let me know if it works.

Thnaks,
Madiha

**Comment by Songmg-Nwafu** [comment] 2024-11-06 01:19
yeah，I'm facing the same problem at the " Identification of Local mis-assemblies/false chimeras"

**Comment by jy-ai** [comment] 2024-11-06 02:19
Hi Madiha,
Thank you for getting back to me.

In the roast-compile.sh file, I replaced 
`unzip external_tools/cufflinks `
with 
`unzip external_tools/cufflinks.zip -d external_tools/ `
and then it was executed successfully.

Thanks,
Jy

**Comment by Shabbirm21** [comment] 2024-11-06 10:57
Hi @Songmg-Nwafu , did you try the above suggested changes.
@jy-ai  thanks for letting me know, i am glad it worked. I am closing it now.

Thanks,
Madiha

**Closed as completed by Shabbirm21** 2024-11-06 10:57 UTC

**Comment by Songmg-Nwafu** [comment] 2024-11-06 12:56
It worked! Thank you
